apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: polaris
spec:
  replicas: 10
  selector:
    matchLabels: # Informar os pods atribuídos a esse deployment, através de um label
      app: nginx-deployment
  strategy: {}
  template: # Configurações do template para criação dos pods
    metadata:
      labels:
        app: nginx-deployment
    spec: # Especificações dos pods
      containers:
      - image: nginx:1.15.0
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.3"
            memory: 64Mi
